name: 构建发包

# 触发工作流的事件
on:
    # 有新tag时触发
    push:
        tags:
            - "v**"

    # 允许手动触发
    workflow_dispatch:

# 执行构建流程
jobs:
    publish-npm:
        # 指定运行环境
        runs-on: ubuntu-latest
        steps:
            # 拉取代码
            - uses: actions/checkout@v3
            # 设置 node 环境
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            # 设置 pnpm
            - uses: pnpm/action-setup@v2.4.0
            - run: pnpm i
            - run: pnpm run build
              # - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
