# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 构建发包

# 触发工作流的事件
on:
  release:
    types: [created]

# 执行构建流程
jobs:
  publish-npm:
  # 指定运行环境
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v3
      # 设置 node 环境
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # 设置 pnpm
      - uses: pnpm/action-setup@v2.4.0
      - run: pnpm i
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
